name: Build and deploy .NET Core application to Function JediAcademy-Api
'on':
  push:
    branches:
      - main
env:
  AZURE_FUNCTIONAPP_NAME: JediAcademy-Api
  AZURE_FUNCTIONAPP_PACKAGE_PATH: Holonet.Jedi.Academy.Api\published
  CONFIGURATION: Release
  DOTNET_VERSION: 6.0.x
  WORKING_DIRECTORY: Holonet.Jedi.Academy.Api
  
jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: release
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }} # Remove publish-profile to use Azure RBAC
